"""initial schema

Revision ID: 757d3d2b0e92
Revises: 
Create Date: 2026-04-10 18:45:59.061856
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '757d3d2b0e92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fixed_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_fixed_schedules_fixed_schedule_window')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fixed_schedules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixed_schedules'))
    )
    op.create_index(op.f('ix_fixed_schedules_end_at'), 'fixed_schedules', ['end_at'], unique=False)
    op.create_index(op.f('ix_fixed_schedules_start_at'), 'fixed_schedules', ['start_at'], unique=False)
    op.create_index(op.f('ix_fixed_schedules_user_id'), 'fixed_schedules', ['user_id'], unique=False)
    op.create_table('flexible_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('min_session_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_session_minutes', sa.Integer(), nullable=False),
    sa.Column('max_minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'in_progress', 'completed', 'cancelled', name='flexibletaskstatus'), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flexible_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flexible_tasks'))
    )
    op.create_index(op.f('ix_flexible_tasks_due_at'), 'flexible_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_flexible_tasks_user_id'), 'flexible_tasks', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('study', 'health', 'work', 'habit', 'general', name='goalcategory'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'archived', name='goalstatus'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index(op.f('ix_goals_category'), 'goals', ['category'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('ai_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strategy_json', sa.JSON(), nullable=False),
    sa.Column('recommendations_json', sa.JSON(), nullable=False),
    sa.Column('raw_plan_json', sa.JSON(), nullable=False),
    sa.Column('llm_mode', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='planstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_ai_plans_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_plans'))
    )
    op.create_index(op.f('ix_ai_plans_goal_id'), 'ai_plans', ['goal_id'], unique=False)
    op.create_index(op.f('ix_ai_plans_user_id'), 'ai_plans', ['user_id'], unique=False)
    op.create_table('allocated_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flexible_task_id', sa.Integer(), nullable=False),
    sa.Column('title_snapshot', sa.String(length=200), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('scheduled_end > scheduled_start', name=op.f('ck_allocated_tasks_allocated_task_window')),
    sa.ForeignKeyConstraint(['flexible_task_id'], ['flexible_tasks.id'], name=op.f('fk_allocated_tasks_flexible_task_id_flexible_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_allocated_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocated_tasks'))
    )
    op.create_index(op.f('ix_allocated_tasks_flexible_task_id'), 'allocated_tasks', ['flexible_task_id'], unique=False)
    op.create_index(op.f('ix_allocated_tasks_scheduled_end'), 'allocated_tasks', ['scheduled_end'], unique=False)
    op.create_index(op.f('ix_allocated_tasks_scheduled_start'), 'allocated_tasks', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_allocated_tasks_user_id'), 'allocated_tasks', ['user_id'], unique=False)
    op.create_table('ai_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_plan_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=80), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_schedulable', sa.Boolean(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('suggested', 'scheduled', 'completed', 'skipped', name='planitemstatus'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_plan_id'], ['ai_plans.id'], name=op.f('fk_ai_plan_items_ai_plan_id_ai_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_ai_plan_items_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_plan_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_plan_items'))
    )
    op.create_index(op.f('ix_ai_plan_items_ai_plan_id'), 'ai_plan_items', ['ai_plan_id'], unique=False)
    op.create_index(op.f('ix_ai_plan_items_goal_id'), 'ai_plan_items', ['goal_id'], unique=False)
    op.create_index(op.f('ix_ai_plan_items_scheduled_end'), 'ai_plan_items', ['scheduled_end'], unique=False)
    op.create_index(op.f('ix_ai_plan_items_scheduled_start'), 'ai_plan_items', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_ai_plan_items_user_id'), 'ai_plan_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_plan_items_user_id'), table_name='ai_plan_items')
    op.drop_index(op.f('ix_ai_plan_items_scheduled_start'), table_name='ai_plan_items')
    op.drop_index(op.f('ix_ai_plan_items_scheduled_end'), table_name='ai_plan_items')
    op.drop_index(op.f('ix_ai_plan_items_goal_id'), table_name='ai_plan_items')
    op.drop_index(op.f('ix_ai_plan_items_ai_plan_id'), table_name='ai_plan_items')
    op.drop_table('ai_plan_items')
    op.drop_index(op.f('ix_allocated_tasks_user_id'), table_name='allocated_tasks')
    op.drop_index(op.f('ix_allocated_tasks_scheduled_start'), table_name='allocated_tasks')
    op.drop_index(op.f('ix_allocated_tasks_scheduled_end'), table_name='allocated_tasks')
    op.drop_index(op.f('ix_allocated_tasks_flexible_task_id'), table_name='allocated_tasks')
    op.drop_table('allocated_tasks')
    op.drop_index(op.f('ix_ai_plans_user_id'), table_name='ai_plans')
    op.drop_index(op.f('ix_ai_plans_goal_id'), table_name='ai_plans')
    op.drop_table('ai_plans')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_category'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_flexible_tasks_user_id'), table_name='flexible_tasks')
    op.drop_index(op.f('ix_flexible_tasks_due_at'), table_name='flexible_tasks')
    op.drop_table('flexible_tasks')
    op.drop_index(op.f('ix_fixed_schedules_user_id'), table_name='fixed_schedules')
    op.drop_index(op.f('ix_fixed_schedules_start_at'), table_name='fixed_schedules')
    op.drop_index(op.f('ix_fixed_schedules_end_at'), table_name='fixed_schedules')
    op.drop_table('fixed_schedules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
