"""add day_of_week to fixed_schedules

Revision ID: a2b8d9a5a237
Revises: 757d3d2b0e92
Create Date: 2026-05-01 13:24:24.454676
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a2b8d9a5a237'
down_revision = '757d3d2b0e92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS tasks CASCADE')
    op.execute('DROP TABLE IF EXISTS user_testing CASCADE')
    op.execute('DROP TABLE IF EXISTS recurring_schedule CASCADE')
    op.execute('DROP TABLE IF EXISTS user_badges CASCADE')
    op.execute('DROP TABLE IF EXISTS goals_testing CASCADE')
    op.add_column('fixed_schedules', sa.Column('day_of_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_schedules', 'day_of_week')
    op.create_table('goals_testing',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False, comment='목표의 이름'),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True, comment='목표 달성 예정일'),
    sa.Column('progress_rate', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='진행률'),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='최종 달성 여부'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('goals_pkey'))
    )
    op.create_table('user_badges',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('badge_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_badges_pkey'))
    )
    op.create_table('recurring_schedule',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('freq_type', postgresql.ENUM('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='freq_type_enum'), server_default=sa.text("'WEEKLY'::freq_type_enum"), autoincrement=False, nullable=True, comment='반복 유형'),
    sa.Column('by_day', sa.TEXT(), autoincrement=False, nullable=True, comment='반복 요일 정보'),
    sa.Column('by_month_day', sa.BIGINT(), autoincrement=False, nullable=True, comment='월간반복일자'),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True, comment='유저 식별'),
    sa.Column('series_id', sa.TEXT(), autoincrement=False, nullable=True, comment='같은 일정 묶음 식별 id'),
    sa.Column('rule_id', sa.TEXT(), autoincrement=False, nullable=True, comment='같은 묶음 안의 반복규칙 식별 id'),
    sa.Column('biweekly_start_date', sa.DATE(), autoincrement=False, nullable=True, comment='격주 일정 시작기준날짜'),
    sa.Column('month_rule', postgresql.ENUM('DAY', 'START', 'MID', 'END', name='month_rule_enum'), autoincrement=False, nullable=True, comment='월반복 방식'),
    sa.Column('color_key', sa.TEXT(), autoincrement=False, nullable=True, comment='동일일정 식별을 위한 시각화용 색상 키'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='생성 시간'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='마지막으로 업데이트 한 시간'),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('by_month_day < 32', name=op.f('recurring_schedule_by_month_day_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('recurring_schedule_pkey')),
    comment='고정적으로 반복될 스케줄 테이블'
    )
    op.create_table('user_testing',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sleep_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('sleep_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_profiles_pkey'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estimated_time', sa.BIGINT(), autoincrement=False, nullable=True, comment='소요시간'),
    sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('level', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='마감 기한'),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True, comment='유저 식별'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='마지막으로 업데이트 한 시간'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='항목이 생성된 시간'),
    sa.Column('scheduled_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='실제 배정된 시작시간'),
    sa.Column('scheduled_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='실제 배정된 종료시간'),
    sa.Column('fail_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='실패 사유'),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='우선순위'),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('level > 0', name=op.f('tasks_level_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    # ### end Alembic commands ###
