"""fix timezone for end_at field

Revision ID: c524cca406e7
Revises: 0470bb2f398d
Create Date: 2026-05-01 18:31:02.308178
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c524cca406e7'
down_revision = '0470bb2f398d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixed_schedules', 'end_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixed_schedules', 'end_at',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
